keys:
  - &primary age1mxefy5ex55x82e0fstz4qrw7xrqtwcrsu342ddlf9w9ehdkuwvts9k6qfz

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|hell|retard)$
    key_groups:
      - age:
          - *primary
